import React, { useState } from 'react';
import { Moon, Printer, MessageSquare, X, CheckCircle2, Wallet, ArrowDownLeft, ArrowUpRight } from 'lucide-react';

interface EndOfDayModalProps {
  onClose: () => void;
  cashSalesPKR: number;
  creditSalesPKR: number;
  totalSalesPKR: number;
  expensesPKR: number;
  purchasesPKR: number;
  grossProfitPKR: number;
  netCashInHandPKR: number;
}

export const EndOfDayModal: React.FC<EndOfDayModalProps> = ({
  onClose,
  cashSalesPKR,
  creditSalesPKR,
  totalSalesPKR,
  expensesPKR,
  purchasesPKR,
  grossProfitPKR,
  netCashInHandPKR,
}) => {
  const [countedCashInput, setCountedCashInput] = useState('');
  const countedCashPKR = countedCashInput === '' ? null : Number(countedCashInput);
  const cashDifferencePKR =
    countedCashPKR === null || !Number.isFinite(countedCashPKR)
      ? null
      : countedCashPKR - netCashInHandPKR;
  const dateStr = new Date().toLocaleDateString('en-PK', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const handleShareWhatsApp = () => {
    const text = encodeURIComponent(
      `*End of Day Summary - ${dateStr}*\n\n` +
      `*SALES:*\n• Cash Sales: Rs. ${cashSalesPKR}\n• Credit: Rs. ${creditSalesPKR}\n• Total Sales: Rs. ${totalSalesPKR}\n\n` +
      `*OUTFLOWS:*\n• Expenses: Rs. ${expensesPKR}\n• Purchases: Rs. ${purchasesPKR}\n\n` +
      `*Gross Profit:* Rs. ${grossProfitPKR}\n` +
      `*💰 Net Cash in Hand:* Rs. ${netCashInHandPKR}\n\n` +
      `_Generated by the pharmacy management system_`
    );
    window.open(`https://wa.me/?text=${text}`, '_blank');
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="visual-modal-panel bg-white rounded-3xl max-w-sm w-full p-6 shadow-2xl border border-slate-200 space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between border-b pb-3">
          <div>
            <h3 className="text-base font-black text-slate-900 flex items-center gap-2">
              <span>🌙</span> End of Day Summary
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">{dateStr}</p>
          </div>
          <button
            onClick={onClose}
            className="p-1 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-100"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Breakdown */}
        <div className="space-y-3 text-xs">
          {/* Sales */}
          <div>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">
              SALES
            </span>
            <div className="space-y-1.5 bg-slate-50 p-2.5 rounded-xl border border-slate-100">
              <div className="flex justify-between">
                <span className="text-slate-600">Cash Sales</span>
                <span className="font-mono font-bold text-slate-900">Rs. {cashSalesPKR}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-600">Credit</span>
                <span className="font-mono font-bold text-slate-900">Rs. {creditSalesPKR}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-600">Returns</span>
                <span className="font-mono font-bold text-slate-500">Unavailable</span>
              </div>
              <div className="flex justify-between border-t border-slate-200 pt-1 font-bold">
                <span className="text-slate-800">Total Sales</span>
                <span className="font-mono text-slate-900">Rs. {totalSalesPKR}</span>
              </div>
            </div>
          </div>

          {/* Outflows */}
          <div>
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-1">
              OUTFLOWS
            </span>
            <div className="space-y-1.5 bg-slate-50 p-2.5 rounded-xl border border-slate-100">
              <div className="flex justify-between">
                <span className="text-slate-600">Expenses</span>
                <span className="font-mono text-red-600 font-bold">Rs. {expensesPKR}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-600">Cash Purchases</span>
                <span className="font-mono text-red-600 font-bold">Rs. {purchasesPKR}</span>
              </div>
            </div>
          </div>

          {/* Profit */}
          <div className="flex justify-between py-1 px-2 text-xs font-bold text-teal-800 bg-teal-50 rounded-lg border border-teal-200">
            <span>Gross Profit</span>
            <span className="font-mono">Rs. {grossProfitPKR}</span>
          </div>

          {/* Net Cash in Hand (Big Green Box) */}
          <div className="p-3 bg-emerald-50 rounded-2xl border border-emerald-300 flex items-center justify-between text-emerald-950">
            <span className="font-bold flex items-center gap-1.5">
              <span>💰</span> Net Cash in Hand
            </span>
            <span className="text-xl font-black font-mono text-emerald-700">
              Rs. {netCashInHandPKR}
            </span>
          </div>
          <div className="space-y-2 rounded-xl border border-border bg-white p-3">
            <label htmlFor="counted-cash" className="block font-bold text-text">
              Counted cash (Rs)
            </label>
            <input
              id="counted-cash"
              type="number"
              min="0"
              step="1"
              value={countedCashInput}
              onChange={(event) => setCountedCashInput(event.target.value)}
              className="w-full rounded-control border border-border px-3 py-2 text-text focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
              placeholder="Enter counted cash"
            />
            <div className="flex justify-between text-xs">
              <span className="text-muted">Difference</span>
              <strong className={cashDifferencePKR !== null && cashDifferencePKR < 0 ? 'text-danger' : 'text-primary'}>
                {cashDifferencePKR === null
                  ? 'Enter counted cash'
                  : `Rs ${cashDifferencePKR.toLocaleString('en-PK')}`}
              </strong>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2 pt-2 border-t">
          <button
            onClick={() => window.print()}
            className="flex-1 py-2 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 rounded-xl flex items-center justify-center gap-1.5 shadow-sm transition"
          >
            <Printer className="w-3.5 h-3.5" /> Print
          </button>
          <button
            onClick={handleShareWhatsApp}
            className="flex-1 py-2 text-xs font-bold text-white bg-emerald-600 hover:bg-emerald-700 rounded-xl flex items-center justify-center gap-1.5 shadow-sm transition"
          >
            <MessageSquare className="w-3.5 h-3.5" /> WhatsApp
          </button>
          <button
            onClick={onClose}
            className="px-3.5 py-2 text-xs font-semibold text-slate-500 hover:bg-slate-100 rounded-xl transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
